/**
 * Shared validation primitives.
 *
 * Postgres CHECK constraints and NUMERIC(precision, scale) limits from
 * db/schema.sql cannot be expressed in prisma/schema.prisma, so they are
 * enforced here instead — this module is where those database rules are
 * mirrored in application code.
 */

import { z } from "zod";

/** Primary keys are UUIDs generated by `gen_random_uuid()`. */
export const uuidSchema = z.uuid();

export const idParamSchema = z.object({ id: uuidSchema });

/** Non-empty, trimmed text for names, titles, units, and other short fields. */
export const shortText = (max = 120) => z.string().trim().min(1).max(max);

/** Free text that may be explicitly cleared by sending null. */
export const nullableText = (max = 2000) => z.string().trim().max(max).nullable();

/** Organization slugs: lowercase, digits, single hyphens between segments. */
export const slugSchema = z
  .string()
  .trim()
  .min(2)
  .max(64)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, {
    error: "Use lowercase letters, numbers, and single hyphens.",
  });

/** DATE columns. Accepts `YYYY-MM-DD` or a Date; always yields a Date. */
export const dateOnlySchema = z
  .union([z.date(), z.iso.date()])
  .transform((value) =>
    typeof value === "string" ? new Date(`${value}T00:00:00.000Z`) : value,
  );

/** TIMESTAMPTZ columns. Accepts an ISO datetime or a Date; yields a Date. */
export const timestampSchema = z
  .union([z.date(), z.iso.datetime({ offset: true, local: true })])
  .transform((value) => (typeof value === "string" ? new Date(value) : value));

function decimalPlaces(value: number): number {
  const text = value.toString();
  if (text.includes("e") || text.includes("E")) {
    const [mantissa, exponent] = text.split(/[eE]/);
    const shift = Number(exponent);
    const existing = mantissa.split(".")[1]?.length ?? 0;
    return shift < 0 ? existing + Math.abs(shift) : Math.max(existing - shift, 0);
  }
  return text.split(".")[1]?.length ?? 0;
}

interface DecimalOptions {
  /** Total digits, matching NUMERIC(precision, scale). */
  precision: number;
  /** Digits after the decimal point. */
  scale: number;
  /** Inclusive lower bound, e.g. 0 for `CHECK (quantity >= 0)`. */
  min?: number;
  /** Exclusive lower bound, e.g. 0 for `CHECK (quantity > 0)`. */
  exclusiveMin?: number;
}

/**
 * Builds a number schema matching a NUMERIC(precision, scale) column plus its
 * CHECK constraint. Values are validated as JS numbers; Prisma widens them to
 * Decimal on write.
 */
export function decimalSchema({
  precision,
  scale,
  min,
  exclusiveMin,
}: DecimalOptions) {
  const limit = 10 ** (precision - scale);

  let schema = z
    .number()
    .refine((value) => Number.isFinite(value), {
      error: "Must be a finite number.",
    })
    .refine((value) => decimalPlaces(value) <= scale, {
      error: `Must have at most ${scale} decimal place${scale === 1 ? "" : "s"}.`,
    })
    .refine((value) => Math.abs(value) < limit, {
      error: `Must be smaller than ${limit} to fit NUMERIC(${precision}, ${scale}).`,
    });

  if (min !== undefined) {
    schema = schema.min(min);
  }
  if (exclusiveMin !== undefined) {
    schema = schema.gt(exclusiveMin);
  }

  return schema;
}

/**
 * Offset-based pagination (`?limit=&offset=`) for list endpoints. Values
 * arrive as query strings, so they are coerced.
 */
export const offsetPaginationSchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(25),
  offset: z.coerce.number().int().min(0).default(0),
});

export type OffsetPagination = z.infer<typeof offsetPaginationSchema>;

/** Guards `update` payloads against a no-op write. */
export const hasAtLeastOneKey = (value: object) => Object.keys(value).length > 0;

export const atLeastOneFieldError = {
  error: "Provide at least one field to update.",
};

/**
 * Booleans arriving in a query string. `z.coerce.boolean()` cannot be used:
 * it applies JS truthiness, so the string "false" would parse as `true`.
 */
export const booleanQueryParam = z
  .enum(["true", "false", "1", "0"])
  .transform((value) => value === "true" || value === "1");

/**
 * Free-text search term for list endpoints. Trimmed, and capped so a filter
 * cannot become an unbounded LIKE pattern.
 */
export const searchTermSchema = z.string().trim().min(1).max(120);

/**
 * Wraps a numeric schema so it also accepts the string form a query parameter
 * arrives in. `decimalSchema` validates JS numbers, so `?maxPricePerKg=12.50`
 * would otherwise fail before its bounds were ever checked.
 */
export function numericQueryParam<T extends z.ZodType<number, unknown>>(schema: T) {
  return z.preprocess(
    (value) => (typeof value === "string" && value.trim() !== "" ? Number(value) : value),
    schema,
  );
}
